// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8TBfup4OlNkc-c9flxNy3sK53jH9AT4A',
    appId: '1:691659161660:web:d47b3227da55e677c44339',
    messagingSenderId: '691659161660',
    projectId: 'new-ebus',
    authDomain: 'new-ebus.firebaseapp.com',
    storageBucket: 'new-ebus.firebasestorage.app',
    measurementId: 'G-9K6YJJY7Y6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDadc8wQL5AZ6n5hekTc3h4HmHQ6gVh-20',
    appId: '1:691659161660:android:de6a0d6012df5a94c44339',
    messagingSenderId: '691659161660',
    projectId: 'new-ebus',
    storageBucket: 'new-ebus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE7FyzQmBCKZ1HgcrZT2cPCj6KXPBlkZw',
    appId: '1:691659161660:ios:f75f37eb1b366f7ec44339',
    messagingSenderId: '691659161660',
    projectId: 'new-ebus',
    storageBucket: 'new-ebus.firebasestorage.app',
    iosBundleId: 'com.example.newEbus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE7FyzQmBCKZ1HgcrZT2cPCj6KXPBlkZw',
    appId: '1:691659161660:ios:f75f37eb1b366f7ec44339',
    messagingSenderId: '691659161660',
    projectId: 'new-ebus',
    storageBucket: 'new-ebus.firebasestorage.app',
    iosBundleId: 'com.example.newEbus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8TBfup4OlNkc-c9flxNy3sK53jH9AT4A',
    appId: '1:691659161660:web:db1fe830b972de0ec44339',
    messagingSenderId: '691659161660',
    projectId: 'new-ebus',
    authDomain: 'new-ebus.firebaseapp.com',
    storageBucket: 'new-ebus.firebasestorage.app',
    measurementId: 'G-NREXM6EZSX',
  );
}
